export * from './common/contracts';
export * from './common/types';
export { generateNonce } from './common/helpers';
export * from './common/utils/resolver';
export * from './core/CIP2';
export { checkSignature } from './core/CIP8';
export * from './providers';
export * from './scripts';
export * from './transaction';
export * from './wallet';
console.log('this is local forked mesh 12-4-2022');
